# -*- coding: utf-8 -*-
"""Tenserflow_using_keras_api.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11E9PfjSSUjdM_UEAag4ytgsImZlH7J9A
"""

import tensorflow as tf

#loading Our datasets
mnist=tf.keras.datasets.mnist

(x_train,y_train),(x_test,y_test)=mnist.load_data()
x_train=tf.keras.utils.normalize(x_train,axis=1)
x_test=tf.keras.utils.normalize(x_test,axis=1)

model=tf.keras.models.Sequential()
model.add(tf.keras.layers.Flatten(input_shape=x_train[0].shape))
model.add(tf.keras.layers.Dense(128,activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(128,activation=tf.nn.relu))

model.add(tf.keras.layers.Dense(10,activation=tf.nn.softmax))

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

model.fit(x_train,y_train,epochs=5)

val_loss,val_accuracy=model.evaluate(x_test,y_test)
print(val_loss,val_accuracy)

model.save('epic_num_reader.model')

new_model=tf.keras.models.load_model('epic_num_reader.model')

predictions=new_model.predict(x_test)

print(predictions)

import numpy as np
print(np.argmax(predictions[78]))

import matplotlib.pyplot as plt
plt.imshow(x_test[78])



